services:
  test_uniandes-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: test_uniandes
    ports:
      - "8000:8000"
    environment:
      - ENV=staging
    volumes:
      - ./data:/app/data
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
